Repository ZHU-ARTCC/artccmgr, pull requests merged in 2018-02, with the labels that each got.

#8 Updated rspec, coverage, and added specs for regions, divisions, and facilities
  .gitignore
  .haml-lint.yml
  .haml-lint_todo.yml
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
  app/models/vatsim.rb
  app/models/vatsim/division.rb
  app/models/vatsim/facility.rb
  app/models/vatsim/region.rb
  config/application.rb
  db/migrate/20180214071930_enable_pgcrypto_extension.rb
  db/migrate/20180214071940_install_audited.rb
  db/migrate/20180214071955_create_vatsim_regions.rb
  db/migrate/20180214072906_create_vatsim_divisions.rb
  db/migrate/20180214072923_create_vatsim_facilities.rb
  db/schema.rb
  lib/tasks/.keep
  lib/tasks/Simplecov.rake
  spec/factories/vatsim_divisons.rb
  spec/factories/vatsim_facilities.rb
  spec/factories/vatsim_regions.rb
  spec/models/vatsim/division_spec.rb
  spec/models/vatsim/facility_spec.rb
  spec/models/vatsim/region_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/support/factory_bot.rb
  spec/support/shoulda_matchers.rb
Labels: enhancement

#9 Added Vatsim ratings model
  app/models/vatsim/rating.rb
  db/migrate/20180214174444_create_vatsim_ratings.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/vatsim_ratings.rb
  spec/models/vatsim/rating_spec.rb
Labels: enhancement

#11 Installed Devise and configured initial User model
  Gemfile
  Gemfile.lock
  README.md
  app/models/user.rb
  app/models/vatsim/facility.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/201802141744445_devise_create_users.rb
  db/schema.rb
  spec/factories/users.rb
  spec/models/user_spec.rb
  spec/models/vatsim/facility_spec.rb
Labels: enhancement

#13 Fixed sequence number of devise user table creation
  db/migrate/20180214174445_devise_create_users.rb
  db/schema.rb
Labels: bug

#15 updated rspec tests for #14
  app/models/vatsim/rating.rb
  spec/models/vatsim/rating_spec.rb
Labels: enhancement

#16 Added Training Blocks and Progress models
  app/models/training.rb
  app/models/training/block.rb
  app/models/training/progress.rb
  app/models/user.rb
  app/models/vatsim/rating.rb
  db/migrate/20180215055805_create_training_blocks.rb
  db/migrate/20180215055806_create_training_progresses.rb
  db/schema.rb
  spec/factories/training_blocks.rb
  spec/factories/training_progresses.rb
  spec/models/training/block_spec.rb
  spec/models/training/progress_spec.rb
  spec/models/user_spec.rb
  spec/models/vatsim/rating_spec.rb
Labels: enhancement

#18 OTS Recommendations and Result / Fixed Vatsim Rating factory and sequencing
  app/models/training/ots.rb
  app/models/training/ots/recommendation.rb
  app/models/training/ots/result.rb
  app/models/user.rb
  app/models/vatsim/rating.rb
  db/migrate/20180215224647_create_training_ots_recommendations.rb
  db/migrate/20180216004251_create_training_ots_results.rb
  db/schema.rb
  spec/factories/training_ots_recommendations.rb
  spec/factories/training_ots_results.rb
  spec/factories/vatsim_ratings.rb
  spec/models/training/ots/recommendation_spec.rb
  spec/models/training/ots/result_spec.rb
  spec/models/user_spec.rb
  spec/models/vatsim/rating_spec.rb
  spec/rails_helper.rb
Labels: bug, enhancement

#19 Added OTS recommendation validations
  app/models/training/ots/recommendation.rb
  app/models/training/ots/result.rb
  spec/models/training/ots/recommendation_spec.rb
  spec/models/training/ots/result_spec.rb
Labels: enhancement

#20 OTS Recommendation Validations
  app/models/training/ots/recommendation.rb
  app/models/training/progress.rb
  spec/models/training/ots/recommendation_spec.rb
Labels: enhancement

#21 Refactored User methods relating to training and fixed foreign keys
  app/models/training/ots/recommendation.rb
  app/models/user.rb
  db/migrate/20180217193243_change_training_ots_results.rb
  db/migrate/20180217194949_change_training_ots_recommendations.rb
  db/migrate/20180217195550_change_training_progress.rb
  db/migrate/20180217200634_change_training_blocks.rb
  db/schema.rb
  spec/models/user_spec.rb
Labels: enhancement

#22 Travis-CI cache bundler.
  .travis.yml
Labels: enhancement

#23 Create ATC Positions Model
  app/models/atc.rb
  app/models/atc/position.rb
  app/models/concerns/.keep
  app/models/concerns/frequency_validator.rb
  db/migrate/20180215161549_create_atc_positions.rb
  db/schema.rb
  spec/factories/atc_positions.rb
  spec/models/atc/position_spec.rb
Labels: enhancement

#24 Added Training::Sessions and Training::Notes
  app/models/training/block.rb
  app/models/training/note.rb
  app/models/training/ots/result.rb
  app/models/training/progress.rb
  app/models/training/session.rb
  app/models/training/type.rb
  app/models/user.rb
  db/migrate/20180218170229_create_training_types.rb
  db/migrate/20180218171502_create_training_sessions.rb
  db/migrate/20180219170119_create_training_notes.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/training_notes.rb
  spec/factories/training_ots_results.rb
  spec/factories/training_progresses.rb
  spec/factories/training_session.rb
  spec/factories/training_types.rb
  spec/models/training/block_spec.rb
  spec/models/training/note_spec.rb
  spec/models/training/ots/recommendation_spec.rb
  spec/models/training/ots/result_spec.rb
  spec/models/training/progress_spec.rb
  spec/models/training/session_spec.rb
  spec/models/training/type_spec.rb
  spec/models/user_spec.rb
Labels: enhancement

#25 TravisCI: Disable allowed failures.
  .travis.yml
Labels: enhancement

#26 Create settings table.
  app/models/setting.rb
  db/migrate/20180220172430_create_settings.rb
  db/schema.rb
  spec/factories/settings.rb
  spec/models/setting_spec.rb
Labels: enhancement

#27 Addressed race condition issue with training progress
  spec/factories/training_progresses.rb
  spec/models/training/progress_spec.rb
Labels: bug

#28 Initial Frontend
  Gemfile
  Gemfile.lock
  app/assets/images/masthead/1.png
  app/assets/javascripts/application.js
  app/assets/javascripts/home.coffee
  app/assets/stylesheets/_footer.scss
  app/assets/stylesheets/_masthead.scss
  app/assets/stylesheets/_theme.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/home.scss
  app/controllers/application_controller.rb
  app/controllers/home_controller.rb
  app/controllers/omniauth_callbacks_controller.rb
  app/helpers/application_helper.rb
  app/helpers/home_helper.rb
  app/models/setting.rb
  app/models/user.rb
  app/models/vatsim/rating.rb
  app/policies/application_policy.rb
  app/policies/home_policy.rb
  app/views/home/index.html.erb
  app/views/layouts/_alerts.html.erb
  app/views/layouts/_footer.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/layouts/application.html.erb
  app/views/sidebar/_leaderboard.html.erb
  app/views/sidebar/_main.html.erb
  app/views/sidebar/_online.html.erb
  app/views/sidebar/_profile.html.erb
  app/views/sidebar/_weather.html.erb
  config/app.yml
  config/initializers/assets.rb
  config/initializers/devise.rb
  config/routes.rb
  db/migrate/20180220172430_create_settings.rb
  db/migrate/20180220201055_remove_rememberable_from_user.rb
  db/migrate/20180220202223_update_user_indexes_and_keys.rb
  db/migrate/20180221172407_drop_settings.rb
  db/migrate/20180221172727_create_settings.rb
  db/schema.rb
  db/seeds.rb
  spec/controllers/home_controller_spec.rb
  spec/controllers/omniauth_callbacks_controller_spec.rb
  spec/factories/settings.rb
  spec/factories/users.rb
  spec/helpers/application_helper_spec.rb
  spec/helpers/home_helper_spec.rb
  spec/models/setting_spec.rb
  spec/models/training/ots/recommendation_spec.rb
  spec/models/vatsim/rating_spec.rb
  spec/policies/application_policy_spec.rb
  spec/policies/home_policy_spec.rb
  spec/rails_helper.rb
Labels: enhancement
